name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-oyri-version]
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello event"
      - name: Log input parameters
        run: echo "Image name [${{ github.event.inputs.application }}] and version [${{ github.event.inputs.version }}]."
